---
baseURL: "/manual/develop/"
languageCode: "en-us"
title: "Flowave documentation"
theme: "flowave"

markup:
  goldmark:
    renderer:
      unsafe: true

blackfriday:
  plainIDAnchors: true

params:
  canonicalBasePath: "https://docs.flowave.finos.org"
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Documentation"
      url: "/manual"
    - id: "security"
      name: "Security"
      url: "/security"
  section:
    id: "manual"
    version: "develop"
    versionAlias: "0.9"
    versions:
      - "latest"
      - "0.9"
      - "develop"
  github:
    repositoryName: "finos/flowave-docs-manual"
    branch: "main"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
...
